# Generated by Django 6.0.1 on 2026-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
