# Generated by Django 6.0.1 on 2026-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_user", "0002_guestemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
