# Generated by Django 6.0.1 on 2026-02-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guest_user", "0003_usersettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatHistory",
        ),
    ]
